import type { Metadata } from "next";
import "../globals.css";
import ClientLandingLayout from "@/components/layout/ClientLandingLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ClientLandingLayout>{children}</ClientLandingLayout>
      </body>
    </html>
  );
}
