import type { Metadata } from "next";
import "../globals.css";
import LandingLayout from "@/components/layout/LandingLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    images: ["/og.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <LandingLayout>{children}</LandingLayout>
      </body>
    </html>
  );
}
